---
- name: Clone kernel
  git:
    repo: https://github.com/raspberrypi/linux.git
    dest: "{{ global_cache_dir }}/rpi3-kernel"
    version: "rpi-{{ bootstrap_kernel_version }}"
    depth: 1
    force: yes

- name: Insert extra version to kernel
  lineinfile:
    dest: "{{ global_cache_dir }}/rpi3-kernel/Makefile"
    regexp: "^EXTRAVERSION = "
    line: "EXTRAVERSION = {{ bootstrap_extraversion }}"

- name: Configure kernel
  copy:
    src: "{{ global_cache_dir }}/rpi3-kernel/arch/arm64/configs/bcmrpi3_defconfig"
    dest: "{{ global_cache_dir }}/rpi3-kernel/.config"
    remote_src: True

- name: Run oldconfig
  shell:
    cmd: "yes '' | make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- oldconfig"
    chdir: "{{ global_cache_dir }}/rpi3-kernel"
  register: out
  changed_when: "'NEW' in out.stdout"

- name: Build kernel
  command:
    cmd: "make -j {{ global_cores }} ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- Image modules dtbs"
    chdir: "{{ global_cache_dir }}/rpi3-kernel"
  register: out
  changed_when: "'LD' in out.stdout"
