---
- import_tasks: prepare.yml
- import_tasks: partitions.yml
- import_tasks: firmware.yml
- import_tasks: kernel.yml
# Mount partitions and add data
- block:
  - import_tasks: mount.yml
  - import_tasks: debootstrap.yml
  - import_tasks: boot.yml
  - import_tasks: user.yml
  rescue:
    - import_tasks: umount.yml
- import_tasks: umount.yml

